# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of ${project.name}
# !-----------------------------------------------------------------------------------------------!
#
# For support join our discord server: https://discord.gg/2rgvQbHsSW
#
#
# -------------------------------------------------------------------------------------------------
# Edit your turret global settings for the display (the messages can be modified in the messages file)
# -------------------------------------------------------------------------------------------------
Turret:
  # Display holograms above turrets
  Display_Holograms: true
  # Display an action bar when a player damages a turret
  Display_Action_Bar: true
  # Should turrets be damageable ?
  Enable_Damageable_Turrets: true
  # The minimum distance between turrets
  Turret_Min_Distance: 2
  # The particle that spawns when the turret is created
  Creation_Particle: "EXPLOSION_LARGE"
  # How big should the particle be set a higher value to make it bigger
  Creation_Particle_Count: 2
  # The sound that is played when the turret is created
  Creation_Sound: "EXPLODE"
  # The particle that spawns when the turret is placed (already created)
  Placement_Particle: "FIREWORKS_SPARK"
  # How big should the particle be set a lower value to make it smaller
  Placement_Particle_Count: 50
  # The sound that is played when the turret is placed
  Placement_Sound: "FIREWORK_BLAST"
  # Should we display a message when a turret kills a player (you can edit the message in the your "messages.yml" file under the "Turret_Display.Turret_Player_Kill_Message" section).
  Enable_Turret_Kill_Message: true
  # If set to true loot will no longer drop when a turret kills a mob (useful if you would like to prevent players to use turrets for farming mobs)
  Remove_Drops_On_Mob_Kill: false
  # Add the worlds you would like turret placement to be disabled
  Blacklisted_Worlds:
    - exampleWolrd
  # If set to true, prevent players from building/placing turrets on enemy territory, they can only build where they're allowed to build.
  # Supported plugins : WorldGuard, Towny, Residence, Konquest, Residence, Medieval Factions, Towny, SaberFactions, FactionsUUID, Lands, KingdomsX
  Build_In_Own_Territory: false
  # If set to true, prevent turrets from targeting allies
  # Supported plugins : Towny, KingdomsX, Lands, SimpleClans, BetterTeams, SaberFactions, FactionsUUID, UltimateClans, Medieval Factions, Konquest, Residence
  Ally_Protection: true

# -------------------------------------------------------------------------------------------------
# Edit your currency settings
# -------------------------------------------------------------------------------------------------
Currency_Settings:
  # If set to false, we will use our own built in economy system that supports MySQL!
  Use_Vault: false
  # Name your currency
  Currency_Name: "coins"
  # How many coins should players get by default (this won't work if your using the Vault economy system)
  Default_Currency: 500

# -------------------------------------------------------------------------------------------------
# MySQL settings (a database system that synchronises data across all of your servers)
# -------------------------------------------------------------------------------------------------
MySQL:
  # Enable or disable MySQL (if enabled, edit the values below to connect this plugin to your database)
  Enable_MySQL: false
  Hostname: "example.hostname"
  Port: 3306
  Database: "database-name"
  Username: "user-name"
  Password: ""

# -------------------------------------------------------------------------------------------------
# What commands should trigger the main plugin command group?
#
# * THE FIRST ALIAS IS THE MAIN LABEL, PLEASE DO NOT REMOVE IT. *
# -------------------------------------------------------------------------------------------------
Command_Aliases: [ laserturrets, turrets, turret, lt ]

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? If it exists, the language file will be copied 
# to your messages/ folder where you can edit it.
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages. You can manually use it with
# {plugin_prefix} variable anywhere.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&c${project.name}&8]&7 "

# -------------------------------------------------------------------------------------------------
# Time of some plugin's operations is measured. You can also use the LagCatcher class to invoke
# this feature. We log a console message if an operation takes over the time below (milliseconds). 
# Set to -1 to disable.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# List of section names that will print informative messages about their features.
# The Debugger class utilizes this key and will only print messages for sections enabled below.
# -------------------------------------------------------------------------------------------------
Debug: [ ]

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# NB: Don't forget to keep this up-to-date with the getConfigVersion method in your Settings class. 
# -------------------------------------------------------------------------------------------------
Version: 4